### ISSUE TITLE
Exceeding letsencrypt cert limit

### ISSUE THREAD

**Issue by akzmonster** [LemmyNet/lemmy-ansible#189] opened 2023-10-15 07:02 UTC
I have been trying to get this thing working for months now and I've had to troubleshoot so many things that are missing from this guide. In doing so, I've had to reset my local machine multiple times and wipe out my VPS every time. But I suppose this has requested a brand new letsencrypt cert every time, and I just hit a limit. I've been locked out for 168 hrs from requesting another.

Do you have any way of implementing a letsencrypt cert retention mechanism so that I can troubleshoot without these limitations?

How would I be able to use an existing cert in a playbook?

**Comment by Nothing4You** [comment] 2023-10-15 11:14
this is currently not configurable in the playbook, but you could comment out these two blocks:

https://github.com/LemmyNet/lemmy-ansible/blob/1.2.0/lemmy.yml#L136-L139

https://github.com/LemmyNet/lemmy-ansible/blob/1.2.0/lemmy.yml#L246-L251

and store the cert in `/etc/letsencrypt/live/$domain/fullchain.pem` along with the private key in `/etc/letsencrypt/live/$domain/privkey.pem`.

if you want to deploy the cert through ansible, you could add `fullchain.pem` and `privkey.pem` to the `files` folder and add the following snippet to `lemmy.yml` after the `Request initial letsencrypt certificate` task:

```yaml
    - name: Create folder for certificates
      ansible.builtin.file:
        path: "/etc/letsencrypt/live/{{ domain }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy certificate files
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "/etc/letsencrypt/live/{{ domain }}/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - fullchain.pem
        - privkey.pem
```

I'm not sure about the production file permissions in this case, but for testing this shouldn't matter.

**Comment by codyro** [comment] 2023-10-16 03:44
We should offer the option to use your own SSL certificate and a variable to enable/disable certbot from running. 

If we're feeling fancy, a variable to have certbot run but using `--dry-run` could be helpful for instances like these as well.

**Comment by ticoombs** [comment] 2023-12-16 09:36
@akzmonster 

I know some time has passed, but would you mind explaining what is missing in our documentation that caused the resulting issue in your case? 
The letsencrypt certificate limit is symptom, not the cause. If we instead try to solve our documentation issues then that would be a better way to ensure no-one in the future has the same issues.

**Comment by ticoombs** [comment] 2024-05-18 11:46
Closing as we now provide the tags to 'not' deploy an ssl certificate.

**Closed** 2024-05-18 11:46 UTC
Labels: question
