### ISSUE TITLE
Problems on Ubuntu 23.04: Unneccessary(?) python modules breaking the installation, deprecated apt-keyring

### ISSUE THREAD

**Issue by darklajid** [LemmyNet/lemmy-ansible#82] opened 2023-06-12 11:38 UTC
Tried getting this up and running on a brand new VPS running 23.04

It failed during the "Install Docker Module and docker-compose for Python" step - `pip3 install -U docker docker-compose` gave a scary warning about mixing system-managed packages with pip and refused to continue. I worked around this by removing this whole part in the playbook: It seems to be merely required for the playbook itself, to run a single docker compose command.

* It fails with my system out-of-the-box
* The docker_compose Ansible plugin seems outdated (requires the legacy `docker-compose` < 2.x instead of the > 2.x `docker compose`)
* It seems not worth pulling in dependencies for a simple, single command

I changed the lemmy.yml with the following diff to make things work:

```
diff --git a/lemmy.yml b/lemmy.yml
index 2c6a7aa..41fa786 100644
--- a/lemmy.yml
+++ b/lemmy.yml
@@ -59,13 +59,6 @@
         state: latest
         update_cache: true
 
-    - name: Install Docker Module and docker-compose for Python
-      pip:
-        name:
-          - docker
-          - docker-compose
-        state: latest
-
     - name: copy docker config
       copy: src='../files/docker-daemon.json' dest='/etc/docker/daemon.json' mode='0644'
 
@@ -160,11 +153,9 @@
     # - debug: var=shell_output
 
     - name: start docker-compose
-      docker_compose:
-        project_src: "{{lemmy_base_dir}}/{{domain}}"
-        state: present
-        pull: yes
-        remove_orphans: yes
+      shell:
+        cmd: docker compose up -d
+        chdir: "{{lemmy_base_dir}}/{{domain}}"
 
     - name: reload nginx with new config
       shell: nginx -s reload

```

After this I now get warnings running apt update:

```
W: https://download.docker.com/linux/ubuntu/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

Arguably that's yet another [outdated plugin](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html) that's doing something it shouldn't.

From the link above / in the Ansible docs:

> The apt-key command has been deprecated and suggests to ‘manage keyring files in trusted.gpg.d instead’. See the Debian wiki for details. This module is kept for backwards compatibility for systems that still use apt-key as the main way to manage apt repository keys.

**Comment by pageuppagedown** [comment] 2023-06-15 02:14
I believe this is also a problem with Debian 13.

**Comment by andrwmorph** [comment] 2023-06-16 21:07
Adding `extra_args: "--break-system-packages"` to the pip task also gets the pip command working. I'm guessing this is probably not a great permanent solution though.

**Comment by eslerm** [comment] 2023-07-01 19:59
The `apt update` issue is solved in https://github.com/LemmyNet/lemmy-ansible/pull/116 and the pip3 issue is a duplicate of https://github.com/LemmyNet/lemmy-ansible/issues/54

Basically, `lemmy-ansible` is running what works in Ubuntu 20.04 (Focal) and isn't aware of difference on Ubuntu 23.04 or Debian 13. Note that you apt warning says you are using `focal` docker binaries.

**Comment by s0ss** [comment] 2023-07-02 03:17
I am seeing the same failures on fresh Debian 12 also.

**Comment by darklajid** [comment] 2023-07-03 04:13
@eslerm The `apt update` fix makes sense and looks good to me (although I'd personally question why a new installation via Ansible needs to still support Focal). 

The reference to 54 seems off though? That is an entirely different issue. In 54 someone has no python2 packages available/literally cannot install apt dependencies. For me pip itself fails and complains that I'm mixing system packages with pip packages¹. I'm arguing here that pip and the outdated ansible docker compose plugin are unnecessary and breaking the installation on newer versions anyway.

I don't think 54 is related at all.

①: Some related python thread for the problem mentioned here: https://discuss.python.org/t/pep-668-marking-python-base-environments-as-externally-managed/10302/72

**Comment by eslerm** [comment] 2023-07-03 14:36
thanks, you are right about 54

**Closed** 2023-07-04 11:33 UTC

**Comment by eslerm** [comment] 2023-07-24 03:28
The apt half of this issue is closed, but pip is still an open issue.

It's not an issue on Ubuntu 22.04, but 23.04 errors:
```
TASK [Install Docker Module and docker-compose for Python] **********************************************************************************************************************************************
fatal: [eslerm@sec-lunar-amd64]: FAILED! => {"changed": false, "cmd": ["/usr/bin/python3", "-m", "pip.__main__", "install", "-U", "docker", "docker-compose"], "msg": "\n:stderr: error: externally-managed-environment\n\n× This environment is externally managed\n╰─> To install Python packages system-wide, try apt install\n    python3-xyz, where xyz is the package you are trying to\n    install.\n    \n    If you wish to install a non-Debian-packaged Python package,\n    create a virtual environment using python3 -m venv path/to/venv.\n    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make\n    sure you have python3-full installed.\n    \n    If you wish to install a non-Debian packaged Python application,\n    it may be easiest to use pipx install xyz, which will manage a\n    virtual environment for you. Make sure you have pipx installed.\n    \n    See /usr/share/doc/python3.11/README.venv for more information.\n\nnote: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.\nhint: See PEP 668 for the detailed specification.\n"}
```

**Comment by darklajid** [comment] 2023-07-24 03:38
@eslerm I agree that this isn't addressed in the pull request that closed this (it just handled the apt keyring changes). You can make things work using my diff from the original post - it works fine for me. Definitely would be good to get this fixed upstream though
